[package]
name = "log_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tklog = "0.3.0"
tokio = { version = "1.48.0", features = ["full"] }
serde_yaml = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }